version: "3.9"  # I uncommented this to ensure the proper versioning

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: "python manage.py runserver 0.0.0.0:8000"  # Simplified the command
